export const PASSWORD_CHANGE_SUCCESS = 'ChangePassword/PASSWORD_CHANGE_SUCCESS';
export const RESET_CHANGE_PASSWORD_PARAMS = 'ChangePassword/RESET_FORGOT_PASSWORD_PARAMS';
export const PASSWORD_CHANGE_FAILURE = 'ChangePassword/PASSWORD_CHANGE_FAILURE';